# Configures JS linting
# https://eslint.org/

# Add third-party configs
extends:
  - standard
  - plugin:import/errors
  - plugin:import/warnings

# Add third-party plugins
plugins:
  - import
  - compat

# Set target environment
env:
  browser: true

# Global scoped method and vars
globals:
  __dirname: true
  require: true
  process: true
  ENV: true
  module: true