# Configures CSS Linting
# https://stylelint.io/
extends:
    - stylelint-config-standard
plugins:
    - stylelint-no-unsupported-browser-features
defaultSeverity: warning
rules:
    plugin/no-unsupported-browser-features:
        - true
        - ignore: []
          severity: warning
